# Generated by Django 4.1.5 on 2023-01-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('icono', models.CharField(max_length=140, verbose_name='icono')),
                ('url', models.CharField(max_length=140, verbose_name='url')),
                ('red_social', models.CharField(max_length=140, verbose_name='url')),
            ],
        ),
    ]
