# Generated by Django 4.1.5 on 2023-01-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_redes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre_mi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('primer_titulo', models.CharField(max_length=140, verbose_name='titulo')),
                ('contenido_principal', models.CharField(max_length=140, verbose_name='contenido')),
                ('tercer_contenido', models.CharField(max_length=140, verbose_name='tercer contenido')),
                ('titulo_uno', models.CharField(max_length=140, verbose_name='titulo 1')),
                ('uno', models.CharField(max_length=140, verbose_name='contenido 1')),
                ('titulo_dos', models.CharField(max_length=140, verbose_name='titulo 2')),
                ('dos', models.CharField(max_length=140, verbose_name='contenido 2')),
                ('titulo_tres', models.CharField(max_length=140, verbose_name='titulo 3')),
                ('tres', models.CharField(max_length=140, verbose_name='contenido 3')),
                ('titulo_cuatro', models.CharField(max_length=140, verbose_name='titulo 4')),
                ('cuatro', models.CharField(max_length=140, verbose_name='contenido 4')),
            ],
        ),
        migrations.AlterField(
            model_name='redes',
            name='icono',
            field=models.CharField(max_length=140, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='redes',
            name='red_social',
            field=models.CharField(max_length=140, verbose_name='red social'),
        ),
        migrations.AlterField(
            model_name='redes',
            name='url',
            field=models.CharField(max_length=140, verbose_name='Url'),
        ),
    ]
