# Generated by Django 4.1.5 on 2023-01-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sobre_mi_contenido_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('header_titulo', models.CharField(max_length=140, verbose_name='Titulo')),
                ('header_contenido', models.CharField(max_length=140, verbose_name='contenido')),
            ],
        ),
    ]
