# Generated by Django 4.1.5 on 2023-01-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_contenido',
            field=models.CharField(max_length=500, verbose_name='contenido'),
        ),
    ]
