# Generated by Django 4.1.5 on 2023-01-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_header_header_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('link', models.CharField(max_length=140, verbose_name='link')),
                ('texto', models.CharField(max_length=500, verbose_name='texto')),
            ],
        ),
    ]
