# Generated by Django 4.1.5 on 2023-01-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_habilidades_items_habilidades_skill_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_items',
            name='id_dos',
            field=models.IntegerField(null=True, verbose_name='id'),
        ),
    ]
