# Generated by Django 4.1.5 on 2023-01-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_header_items_id_dos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('titulo', models.CharField(max_length=140, verbose_name='titulo')),
                ('texto', models.CharField(max_length=50, verbose_name='texto')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('id_dos', models.IntegerField(verbose_name='titulo')),
                ('titulo', models.CharField(max_length=140, verbose_name='titulo')),
                ('titulo_dos', models.CharField(max_length=140, verbose_name='titulo')),
                ('contenido', models.CharField(max_length=500, verbose_name='contenido')),
                ('url', models.CharField(max_length=500, verbose_name='url')),
            ],
        ),
    ]
