# Generated by Django 4.1.5 on 2023-01-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_trabajos_trabajos_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='texto',
            field=models.CharField(max_length=500, verbose_name='texto'),
        ),
    ]
