# Generated by Django 4.1.5 on 2023-01-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_trabajos_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos_items',
            name='nombre_imagen',
            field=models.CharField(max_length=140, null=True, verbose_name='titulo'),
        ),
    ]
