# Generated by Django 4.1.5 on 2023-01-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_trabajos_items_nombre_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos_items',
            name='url_proyecto',
            field=models.CharField(max_length=200, null=True, verbose_name='titulo'),
        ),
    ]
