# Generated by Django 4.1.5 on 2023-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_trabajos_items_url_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('titulo', models.CharField(max_length=140, verbose_name='titulo')),
                ('titulo_dos', models.CharField(max_length=140, verbose_name='titulo')),
                ('titulo_tres', models.CharField(max_length=140, verbose_name='titulo')),
                ('email', models.CharField(max_length=500, verbose_name='contenido')),
            ],
        ),
    ]
