# Generated by Django 3.2.16 on 2023-01-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_faltante_idioma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ip', models.CharField(max_length=140, verbose_name='video')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
