# Generated by Django 3.2.16 on 2023-02-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='pais',
            field=models.CharField(max_length=140, null=True, verbose_name='video'),
        ),
    ]
