# Generated by Django 3.2.16 on 2023-02-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_visitas_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('countrycode', models.CharField(max_length=140, verbose_name='countrycode')),
                ('countryname', models.CharField(max_length=140, verbose_name='countryname')),
                ('code', models.CharField(max_length=140, null=True, verbose_name='code')),
            ],
        ),
    ]
